# Generated by Django 3.2 on 2021-04-23 16:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('introduction', models.CharField(max_length=60, verbose_name='简介')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('imgpic_640x427', imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
