# Generated by Django 3.2 on 2021-04-23 16:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='网站名称')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
