# Generated by Django 3.2 on 2021-04-29 15:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
