# Generated by Django 3.2 on 2021-04-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imgpic_640x427',
        ),
    ]
