# Generated by Django 3.2 on 2021-04-30 09:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_blog_imgpic_640x427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('contents', models.CharField(max_length=30, verbose_name='内容')),
                ('imgpic_640x427', imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
