# Generated by Django 3.2 on 2021-04-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_image_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_list',
            old_name='imgpic_640x427',
            new_name='img',
        ),
    ]
