# Generated by Django 3.2 on 2021-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_imgpic_640x427_image_list_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_list',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
