# Generated by Django 3.2 on 2021-04-30 14:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_image_list_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=30, verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
