# Generated by Django 3.2 on 2021-04-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210430_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='title',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.text', verbose_name='网站名称'),
            preserve_default=False,
        ),
    ]
