# Generated by Django 3.2 on 2021-04-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_websetting_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': '文本', 'verbose_name_plural': '文本'},
        ),
    ]
