# Generated by Django 3.2 on 2021-04-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210430_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='web.text', verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websetting',
            name='phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='web.text', verbose_name='电话'),
            preserve_default=False,
        ),
    ]
