# Generated by Django 3.2 on 2021-05-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20210430_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='web.richtext', verbose_name='关于我们'),
            preserve_default=False,
        ),
    ]
