# Generated by Django 3.2 on 2021-05-02 07:58

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_websetting_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('contents', models.CharField(max_length=30, verbose_name='内容')),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页',
                'verbose_name_plural': '首页',
            },
        ),
        migrations.AddField(
            model_name='websetting',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web.richtext', verbose_name='关于我们'),
            preserve_default=False,
        ),
    ]
