# Generated by Django 3.2 on 2021-05-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210502_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='IndexPage',
        ),
    ]
