# Generated by Django 3.2 on 2021-05-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20210503_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='websetting',
            name='about',
        ),
        migrations.RemoveField(
            model_name='websetting',
            name='products',
        ),
        migrations.RemoveField(
            model_name='websetting',
            name='technology',
        ),
    ]
