# Generated by Django 3.2 on 2021-05-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20210503_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologypage',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.text'),
            preserve_default=False,
        ),
    ]
