# Generated by Django 3.2 on 2021-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_technologypage_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologypage',
            name='list',
        ),
        migrations.AddField(
            model_name='technologypage',
            name='list',
            field=models.ManyToManyField(to='web.Text'),
        ),
    ]
