# Generated by Django 3.2 on 2021-05-04 12:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_text_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologypage',
            name='contents',
        ),
        migrations.AddField(
            model_name='technologypage',
            name='contents1',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='内容1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologypage',
            name='contents2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='内容2'),
            preserve_default=False,
        ),
    ]
