# Generated by Django 3.2 on 2021-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20210504_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='logo',
            field=models.ImageField(help_text='LOGO 分辨率:180*55', upload_to=''),
        ),
    ]
