# Generated by Django 3.2 on 2021-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_websetting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='contents',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
