# Generated by Django 3.2 on 2021-05-07 01:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20210507_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='img1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/about', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img2',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/about', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img3',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/about', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/contact', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/index', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img2',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img3',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img4',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img5',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img6',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img7',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='img8',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/product', verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='technologypage',
            name='img1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/technology', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='technologypage',
            name='img2',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/technology', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='technologypage',
            name='img3',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/technology', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='technologypage',
            name='img4',
            field=imagekit.models.fields.ProcessedImageField(upload_to='Image/technology', verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='logo',
            field=models.ImageField(help_text='LOGO 分辨率:180*55', upload_to='Image/logo'),
        ),
    ]
