# Generated by Django 3.2 on 2021-05-07 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20210507_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='web.text', verbose_name='网站名称'),
        ),
    ]
