# Generated by Django 3.2 on 2021-05-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_alter_websetting_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websetting',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
