# Generated by Django 3.2 on 2021-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20210507_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='email',
            field=models.CharField(max_length=60, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='title',
            field=models.CharField(max_length=60, verbose_name='网站名称'),
        ),
    ]
