# Generated by Django 3.2 on 2021-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20210507_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contents',
        ),
        migrations.AddField(
            model_name='blog',
            name='files',
            field=models.FileField(default=1, upload_to='File'),
            preserve_default=False,
        ),
    ]
